name: Crear EXE Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install opencv-python
          pip install mediapipe==0.10.21
          pip install pillow

      - name: Verificar MediaPipe
        run: |
          python -c "import mediapipe as mp; print('MediaPipe:', mp.__version__); print('Tiene solutions:', hasattr(mp, 'solutions'))"

      - name: Crear programa Windows
        run: |
          pyinstaller --noconfirm --clean --windowed --name "ManosQueHablan" --collect-all mediapipe --hidden-import mediapipe.python.solutions.hands manos_que_hablan_fullscreen_inicio_corregido.py

      - name: Subir EXE
        uses: actions/upload-artifact@v4
        with:
          name: ManosQueHablan-Windows
          path: dist/ManosQueHablan/
